### ISSUE TITLE
Failed: awesome_customers_delivery-acceptance

### ISSUE THREAD

**Issue by dallinwright** [learn-chef/awesome_customers_delivery#3]
I am experience an issue with this cookbook during the chef delivery tutorial on learn.chef.io at this section.

https://learn.chef.io/delivery/get-started/create-the-project/

Here is the output and the failure. It happens in the deploy portion of the acceptance section. I have run into this on 2 different aws stacks using the chef provided cloudformation stack.

``` 
Recipe: delivery-truck::deploy
  * delivery_push_job[deploy_awesome_customers_delivery] action dispatch
    
    ================================================================================
    Error executing action `dispatch` on resource 'delivery_push_job[deploy_awesome_customers_delivery]'
    ================================================================================
    
    DeliverySugar::Exceptions::PushJobFailed
    ----------------------------------------
    The push-job b3f9efc18c5030e50dbd99df1bd9eead failed to complete successfully.
    
    Command: chef-client
    Nodes:
       failed: awesome_customers_delivery-acceptance
    
    
    Cookbook Trace:
    ---------------
    /var/opt/delivery/workspace/10.0.0.12/delivery-demo/delivery-demo/awesome_customers_delivery/master/acceptance/deploy/cache/cookbooks/delivery-sugar/libraries/delivery_push_job.rb:75:in `block in wait'
    /var/opt/delivery/workspace/10.0.0.12/delivery-demo/delivery-demo/awesome_customers_delivery/master/acceptance/deploy/cache/cookbooks/delivery-sugar/libraries/delivery_push_job.rb:72:in `loop'
    /var/opt/delivery/workspace/10.0.0.12/delivery-demo/delivery-demo/awesome_customers_delivery/master/acceptance/deploy/cache/cookbooks/delivery-sugar/libraries/delivery_push_job.rb:72:in `wait'
    /var/opt/delivery/workspace/10.0.0.12/delivery-demo/delivery-demo/awesome_customers_delivery/master/acceptance/deploy/cache/cookbooks/delivery-sugar/libraries/delivery_push_job_provider.rb:59:in `block in action_dispatch'
    /var/opt/delivery/workspace/10.0.0.12/delivery-demo/delivery-demo/awesome_customers_delivery/master/acceptance/deploy/cache/cookbooks/delivery-sugar/libraries/delivery_push_job_provider.rb:56:in `action_dispatch'
    
    Resource Declaration:
    ---------------------
    # In /var/opt/delivery/workspace/10.0.0.12/delivery-demo/delivery-demo/awesome_customers_delivery/master/acceptance/deploy/cache/cookbooks/delivery-truck/recipes/deploy.rb
    
     34:   delivery_push_job "deploy_#{node['delivery']['change']['project']}" do
     35:     command 'chef-client'
     36:     nodes my_nodes
     37:   end
     38: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/opt/delivery/workspace/10.0.0.12/delivery-demo/delivery-demo/awesome_customers_delivery/master/acceptance/deploy/cache/cookbooks/delivery-truck/recipes/deploy.rb:34:in `from_file'
    
    delivery_push_job("deploy_awesome_customers_delivery") do
      provider Chef::Provider::DeliveryPushJob
      action :dispatch
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      command "chef-client"
      timeout 1800
      nodes ["awesome_customers_delivery-acceptance"]
      change #<DeliverySugar::Change:0x000000043a27e0 @workspace_repo="/var/opt/delivery/workspace/10.0.0.12/delivery-demo/delivery-demo/awesome_customers_delivery/master/acceptance/deploy/repo", @workspace_cache="/var/opt/delivery/workspace/10.0.0.12/delivery-demo/delivery-demo/awesome_customers_delivery/master/acceptance/deploy/cache", @workspace_chef="/var/opt/delivery/workspace/10.0.0.12/delivery-demo/delivery-demo/awesome_customers_delivery/master/acceptance/deploy/chef", @workspace_path="/var/opt/delivery/workspace", @enterprise="delivery-demo", @organization="delivery-demo", @stage="acceptance", @project="awesome_customers_delivery", @pipeline="master", @change_id="8dc2c1a8-3761-4b4f-a077-a74c85410b7b", @merge_sha="4bbd81025d8f58dcab0afed7e68b6bc155a85e2f", @patchset_branch="">
      chef_config_file "/var/opt/delivery/workspace/.chef/knife.rb"
      declared_type :delivery_push_job
      cookbook_name "delivery-truck"
      recipe_name "deploy"
    end
    

Running handlers:
[2016-05-04T18:21:27+00:00] ERROR: Running exception handlers
Running handlers complete
[2016-05-04T18:21:27+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 11 seconds
[2016-05-04T18:21:27+00:00] FATAL: Stacktrace dumped to /var/opt/delivery/workspace/10.0.0.12/delivery-demo/delivery-demo/awesome_customers_delivery/master/acceptance/deploy/cache/chef-stacktrace.out
[2016-05-04T18:21:27+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-05-04T18:21:27+00:00] ERROR: The push-job b3f9efc18c5030e50dbd99df1bd9eead failed to complete successfully.

Command: chef-client
Nodes:
   failed: awesome_customers_delivery-acceptance


[2016-05-04T18:21:28+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef Client failed
STDOUT: 
STDERR: 


Job ended at 2016-05-04T18:21:28+00:00 (ran in 24 seconds)
Chef Stacktrace
Generated at 2016-05-04 18:21:27 +0000
DeliverySugar::Exceptions::PushJobFailed: The push-job b3f9efc18c5030e50dbd99df1bd9eead failed to complete successfully.

Command: chef-client
Nodes:
   failed: awesome_customers_delivery-acceptance
```

**Comment by VikasBains** [comment]
@dallinwright
How was this fixed?
